### ISSUE TITLE
Build issues, Windows or Linux?

### ISSUE THREAD

**Issue by teknixstuff** [NeonSky/open-pokemon-tcg#1]
The instructions don't explain if this is for Linux or Windows, however on Windows `sudo` is missing, and on Linux Mint `vcpkg` is missing, and doesn't work even after installation via the vcpkg website. This makes it unclear which OS is required, as `vcpkg` sounds more windows-ish (VC is Visual C++, which is Windows mostly), and `sudo` sounds more linux-ish (installed by default), however there are many versions of `sudo` for Windows.

**Comment by NeonSky** [comment]
Hi. I wrote this project on Arch Linux, but any Linux distro should work. `vcpkg` is a C++ library manager that you would have to download and install separately (https://github.com/microsoft/vcpkg). In the case of Arch Linux, you can find a dedicated package here: https://aur.archlinux.org/packages/vcpkg
